FROM public.ecr.aws/lambda/python:3.10

RUN yum update -y && \
    yum install -y gcc python3-devel git && \
    yum clean all

ADD pyproject.toml requirements.txt .
RUN pip install . && rm pyproject.toml
RUN pip install mangum==0.17.0
COPY mergemate/ ${LAMBDA_TASK_ROOT}/mergemate/

CMD ["mergemate.servers.serverless.serverless"]
